/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariotrivia;

import java.awt.Graphics;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mattia
 */
public class SchermataGiocoPesci extends javax.swing.JFrame {

    ScambioMessaggi scambio;
    GiocoPesci p;
    TimerG t;
    Boolean b;

    /**
     * Creates new form SchermataGiocoPesci
     */
    public SchermataGiocoPesci() {
        initComponents();
    }

    public SchermataGiocoPesci(ScambioMessaggi s) throws IOException {
        initComponents();

        scambio = s;
        p = s.p;
        p.start();
        if (scambio.playerlocale.isHost()) {
            //generare stringa casuale di 6 caratteri separati da ";" da inviare all'utente
            p.random();
            String str = "P;";
            for (int i = 0; i < p.v.size(); i++) {
                str += p.v.get(i) + ";";
            }
            scambio.InviaPacchetto(str);
        }
        new Thread(() -> {
            while (true) {
                System.out.println("Scelta");
                if (p.scelta == 1) {
                    Pesce1.setVisible(false);
                } else if (p.scelta == 2) {
                    Pesce2.setVisible(false);
                } else if (p.scelta == 3) {
                    Pesce3.setVisible(false);
                } else if (p.scelta == 4) {
                    Pesce4.setVisible(false);
                } else if (p.scelta == 5) {
                    Pesce5.setVisible(false);
                } else if (p.scelta == 6) {
                    Pesce6.setVisible(false);
                }
                if (scambio.p.finito) {
                    Mappa m = new Mappa(Condivisa.getInstance().getSc());
                    m.show();
                    this.hide();
                    break;
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Output = new javax.swing.JLabel();
        Pesce1 = new javax.swing.JLabel();
        Pesce2 = new javax.swing.JLabel();
        Pesce3 = new javax.swing.JLabel();
        Pesce4 = new javax.swing.JLabel();
        Pesce5 = new javax.swing.JLabel();
        Pesce6 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesce.png"))); // NOI18N

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(Output);
        Output.setBounds(240, 370, 180, 90);

        Pesce1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesce.png"))); // NOI18N
        Pesce1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pesce1MouseClicked(evt);
            }
        });
        getContentPane().add(Pesce1);
        Pesce1.setBounds(20, 10, 165, 160);

        Pesce2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesce.png"))); // NOI18N
        Pesce2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pesce2MouseClicked(evt);
            }
        });
        getContentPane().add(Pesce2);
        Pesce2.setBounds(200, 10, 165, 160);

        Pesce3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesce.png"))); // NOI18N
        Pesce3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pesce3MouseClicked(evt);
            }
        });
        getContentPane().add(Pesce3);
        Pesce3.setBounds(400, 10, 165, 160);

        Pesce4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesce.png"))); // NOI18N
        Pesce4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pesce4MouseClicked(evt);
            }
        });
        getContentPane().add(Pesce4);
        Pesce4.setBounds(30, 230, 165, 160);

        Pesce5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesce.png"))); // NOI18N
        Pesce5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pesce5MouseClicked(evt);
            }
        });
        getContentPane().add(Pesce5);
        Pesce5.setBounds(220, 230, 165, 160);

        Pesce6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesce.png"))); // NOI18N
        Pesce6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pesce6MouseClicked(evt);
            }
        });
        getContentPane().add(Pesce6);
        Pesce6.setBounds(400, 230, 165, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pesce1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesce1MouseClicked
        // TODO add your handling code here:
        if (p.isTimer()) {
            if (scambio.playerlocale.isTurno() && !scambio.p.finito) {
                if (p.v.get(0).equals("t")) {
                    Output.setText("SceltaCorretta");
                    scambio.playerlocale.aggiungiPunti(2);
                    //codice per inviare la scelta all'altro utente
                } else {
                    Output.setText("SceltaErrata");
                    scambio.p.finito = true;
                    try {
                        scambio.Scrivi("e;perso");
                    } catch (IOException ex) {
                        Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
                try {
                    scambio.Scrivi("E;1");
                    Pesce1.setVisible(false);
                    scambio.playerlocale.setTurno(false);
                } catch (IOException ex) {
                    Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_Pesce1MouseClicked

    private void Pesce2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesce2MouseClicked
        // TODO add your handling code here:
        if (p.isTimer()) {
            if (scambio.playerlocale.isTurno() && !scambio.p.finito) {
                if (p.v.get(1).equals("t")) {
                    Output.setText("SceltaCorretta");
                    scambio.playerlocale.aggiungiPunti(2);
                } else {
                    Output.setText("SceltaErrata");
                    scambio.p.finito = true;
                    try {
                        scambio.Scrivi("e;perso");
                    } catch (IOException ex) {
                        Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
                try {
                    scambio.Scrivi("E;2");
                    Pesce2.setVisible(false);
                    scambio.playerlocale.setTurno(false);
                } catch (IOException ex) {
                    Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_Pesce2MouseClicked

    private void Pesce3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesce3MouseClicked
        // TODO add your handling code here:
        if (p.isTimer()) {
            if (scambio.playerlocale.isTurno() && !scambio.p.finito) {
                if (p.v.get(2).equals("t")) {
                    Output.setText("SceltaCorretta");
                    scambio.playerlocale.aggiungiPunti(2);
                } else {
                    Output.setText("SceltaErrata");
                    scambio.p.finito = true;
                    try {
                        scambio.Scrivi("e;perso");
                    } catch (IOException ex) {
                        Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try {
                    scambio.Scrivi("E;3");
                    Pesce3.setVisible(false);
                    scambio.playerlocale.setTurno(false);
                } catch (IOException ex) {
                    Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_Pesce3MouseClicked

    private void Pesce4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesce4MouseClicked
        // TODO add your handling code here:
        if (p.isTimer()) {
            if (scambio.playerlocale.isTurno() && !scambio.p.finito) {
                if (p.v.get(3).equals("t")) {
                    Output.setText("SceltaCorretta");
                    scambio.playerlocale.aggiungiPunti(2);
                } else {
                    Output.setText("SceltaErrata");
                    scambio.p.finito = true;
                    try {
                        scambio.Scrivi("e;perso");
                    } catch (IOException ex) {
                        Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try {
                    scambio.Scrivi("E;4");
                    Pesce4.setVisible(false);
                    scambio.playerlocale.setTurno(false);
                } catch (IOException ex) {
                    Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_Pesce4MouseClicked

    private void Pesce5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesce5MouseClicked
        // TODO add your handling code here:
        if (p.isTimer()) {
            if (scambio.playerlocale.isTurno() && !scambio.p.finito) {
                if (p.v.get(4).equals("t")) {
                    Output.setText("SceltaCorretta");
                    scambio.playerlocale.aggiungiPunti(2);
                } else {
                    Output.setText("SceltaErrata");
                    scambio.p.finito = true;
                    try {
                        scambio.Scrivi("e;perso");
                    } catch (IOException ex) {
                        Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
                try {
                    scambio.Scrivi("E;5");
                    Pesce5.setVisible(false);
                    scambio.playerlocale.setTurno(false);
                } catch (IOException ex) {
                    Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_Pesce5MouseClicked

    private void Pesce6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesce6MouseClicked
        // TODO add your handling code here:
        if (p.isTimer()) {
            if (scambio.playerlocale.isTurno() && !scambio.p.finito) {
                if (p.v.get(5).equals("t")) {
                    Output.setText("SceltaCorretta");
                    scambio.playerlocale.aggiungiPunti(2);
                } else {
                    Output.setText("SceltaErrata");
                    scambio.p.finito = true;
                    try {
                        scambio.Scrivi("e;perso");
                    } catch (IOException ex) {
                        Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
                try {
                    scambio.Scrivi("E;6");
                    Pesce6.setVisible(false);
                    scambio.playerlocale.setTurno(false);
                } catch (IOException ex) {
                    Logger.getLogger(SchermataGiocoPesci.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_Pesce6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchermataGiocoPesci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchermataGiocoPesci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchermataGiocoPesci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchermataGiocoPesci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchermataGiocoPesci().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Output;
    private javax.swing.JLabel Pesce1;
    private javax.swing.JLabel Pesce2;
    private javax.swing.JLabel Pesce3;
    private javax.swing.JLabel Pesce4;
    private javax.swing.JLabel Pesce5;
    private javax.swing.JLabel Pesce6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
